<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/prase.proto

namespace Parser;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>parser.Input</code>
 */
class Input extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string EncodedHTML = 1;</code>
     */
    protected $EncodedHTML = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $EncodedHTML
     * }
     */
    public function __construct($data = NULL) {
        \GPBMetadata\Proto\Prase::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string EncodedHTML = 1;</code>
     * @return string
     */
    public function getEncodedHTML()
    {
        return $this->EncodedHTML;
    }

    /**
     * Generated from protobuf field <code>string EncodedHTML = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setEncodedHTML($var)
    {
        GPBUtil::checkString($var, True);
        $this->EncodedHTML = $var;

        return $this;
    }

}

