<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/prase.proto

namespace GPBMetadata\Proto;

class Prase
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0ab4010a1170726f746f2f70726173652e70726f746f1206706172736572221c0a05496e70757412130a0b456e636f64656448544d4c180120012809222a0a064f7574707574120d0a055469746c6518012003280912110a0943616e6f6e6963616c18022003280932340a08506172736572494f12280a055061727365120d2e7061727365722e496e7075741a0e2e7061727365722e4f75747075742200420f5a0d7365727665723b736572766572620670726f746f33"
        ), true);

        static::$is_initialized = true;
    }
}

